### ISSUE TITLE
Wouldn't the default path be better with a dot in front?

### ISSUE THREAD

**Issue by JJ** [finanalyst/pod-cached#1]
Same as .precomp now. Or, it could even be `.precomp`, right?

**Comment by finanalyst** [comment]
This is part of a bigger question - I think.  
I suppose that the default could simply be in the CWD of the calling program, and the user can overide the location in any case.  
The bigger issue is whether the cache itself can be bundled without bundling the pod files. I am including a `freeze` method so that methods without a pod collection can still operate with the cache. But I do not know yet whether nqp::at-key will work if the cache is placed in a different directory from the one it was generated at.

**Comment by JJ** [comment]
Maybe @tbrowder can help?

**Comment by tbrowder** [comment]
I’m sorry but I’m deep into pod nqp at the moment and can’t grasp what you two are doing.  My multitasking days are over I’m afraid!

**Comment by JJ** [comment]
Good luck!

**Comment by tbrowder** [comment]
On Wed, Oct 24, 2018 at 6:21 AM Juan Julián Merelo Guervós
<notifications@github.com> wrote:
>
> Good luck!

Thanks, JJ!

**Comment by finanalyst** [comment]
default is '.pod-cache'   
could be '.precomp' but don't want to interfere with name space whilst developing
