### ISSUE TITLE
Add heavy-duty 256 files test

### ISSUE THREAD

**Issue by JJ** [finanalyst/pod-cached#6]
Some problems arise when many files are open, maybe in a threaded environment. My hunch is that the intermitent failure is related to this. If we could golf it down to a test here, that would be great. And if it does not fail, it will prove that it works well and the problem might be in the threads or somewhere else.

**Comment by finanalyst** [comment]
1. Do we know whether the file numbers open is 256, or more?
1. Do we know whether the files have to be con-currently open, or whether they are opened but could be closed?
  - I ask this because if the files have to be con-currently open, then the test sources will need to be created so that it takes some time for them to process.
1. At present, the pod::cached is not written with threads. I will do this. But we could set up the test, get it working without threads, then test with threads later. OK?

**Comment by JJ** [comment]
El mié., 24 oct. 2018 a las 7:32, Richard Hainsworth (<
notifications@github.com>) escribió:

>
>    1. Do we know whether the file numbers open is 256, or more?
>
>
It's in the ballpark of 170. 256 to be on the safe side.

>
>    1. Do we know whether the files have to be con-currently open, or
>    whether they are opened but could be closed?
>
>
>    - I ask this because if the files have to be con-currently open, then
>    the test sources will need to be created so that it takes some time for
>    them to process.
>
> No, I don't think they have to be open at the same time.

>
>
>
>    1. At present, the pod::cached is not written with threads. I will do
>    this. But we could set up the test, get it working without threads, then
>    test with threads later. OK?
>
>
That would be great

**Comment by finanalyst** [comment]
Added heavy-duty test. Passes without problem. No threads yet.
